[project]
name = "hpc-client-gui"
version = "1.2.7"
requires-python = ">=3.10"
dependencies = ["PySide6>=6.5", "paramiko>=3.4", "cryptography>=41.0"]

authors = [{ name = "Mehmed Sinan KÖMEK" }]
license = { text = "PolyForm Noncommercial License 1.0.0" }

[project.optional-dependencies]
test = ["pyftpdlib>=1.5.9", "pytest>=7"]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
hpc_gui = ["assets/**/*.seg", "assets/**/*.png", "docs/*.md", "i18n/*.json"]
